import { getCloudflareContext } from "@opennextjs/cloudflare";

/**
 * POST /api/chart-log — records the birth details a visitor cast a chart from.
 *
 * Fired once per Markdown export, not once per chart: casting is exploratory
 * (people nudge a time by four minutes and recast), while downloading the
 * report is the point at which a chart was actually taken away and used. One
 * row per download is both the smaller write volume and the more meaningful
 * signal.
 *
 * The store is the CHART_LOG_DB D1 binding declared in wrangler.jsonc. A
 * binding rather than an HTTP database is the whole reason this is cheap: the
 * write is a local call inside the same Worker isolate, there is no API token
 * to store or leak, and nothing in the request path leaves Cloudflare. D1's
 * free allowance is 100,000 row-writes a day against one row per download.
 *
 * This route is consequently the one place in the repo that is Cloudflare-
 * specific, which /api/rectify's comment argues against on principle. The
 * difference is that the coupling here is to a *store* and is contained: the
 * binding is read through a guarded call, and an environment without it — a
 * bare `next build`, a fork, a future host — takes the not-configured branch
 * and the site is unaffected rather than broken.
 */
export const dynamic = "force-dynamic";

/** Hard ceiling on every stored string. A visitor controls all of them, and an
 *  unbounded name field is how a free tier becomes a full one. */
const MAX_TEXT = 120;

function text(v: unknown): string | null {
  if (typeof v !== "string") return null;
  const trimmed = v.trim();
  return trimmed ? trimmed.slice(0, MAX_TEXT) : null;
}

function num(v: unknown): number | null {
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}

/**
 * Resolves the D1 binding, or null when there is none.
 *
 * `getCloudflareContext` throws rather than returning undefined when called
 * outside a Worker — which is the normal case for `next build`'s page-data
 * collection and for anyone running the repo without a Cloudflare account —
 * so the throw is caught and treated as "not configured", exactly like a
 * missing binding.
 */
function chartLogDb(): D1Database | null {
  try {
    // `env` is typed from cloudflare-env.d.ts, regenerated by `npm run
    // cf-typegen` whenever wrangler.jsonc changes. The `?? null` is not
    // redundant with that type: the binding is declared present at compile
    // time but genuinely absent at runtime in a Worker deployed before the
    // D1 database was attached.
    return getCloudflareContext().env.CHART_LOG_DB ?? null;
  } catch {
    return null;
  }
}

export async function POST(request: Request): Promise<Response> {
  const db = chartLogDb();

  // Unconfigured is a normal state, not an error: a missing binding must not
  // surface as a failed request beside a download that worked fine.
  if (!db) return json({ logged: false, reason: "not-configured" }, 200);

  let body: Record<string, unknown>;
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    return json({ logged: false, reason: "bad-json" }, 400);
  }

  const row = {
    mode: body.mode === "manual" ? "manual" : "auto",
    native_name: text(body.name),
    gender: text(body.gender),
    birth_date: text(body.dateISO),
    birth_time: text(body.time),
    place_name: text(body.placeName),
    place_admin: text(body.placeAdmin),
    place_country: text(body.placeCountry),
    latitude: num(body.lat),
    longitude: num(body.lon),
    timezone: text(body.timezone),
  };

  // A row with neither a date nor a place carries no information worth a write.
  if (!row.birth_date && !row.place_name) {
    return json({ logged: false, reason: "empty" }, 400);
  }

  try {
    await db
      .prepare(
        `INSERT INTO chart_logs
           (mode, native_name, gender, birth_date, birth_time,
            place_name, place_admin, place_country, latitude, longitude, timezone)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
      )
      .bind(
        row.mode, row.native_name, row.gender, row.birth_date, row.birth_time,
        row.place_name, row.place_admin, row.place_country,
        row.latitude, row.longitude, row.timezone
      )
      .run();
  } catch (err) {
    // Logged for the operator (observability is on in wrangler.jsonc), never
    // echoed to the caller: a D1 error names the table and the constraint.
    console.error("chart-log insert failed", err);
    return json({ logged: false, reason: "store-error" }, 200);
  }

  return json({ logged: true }, 200);
}

function json(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json; charset=utf-8" },
  });
}
